mixed-port: 7890
allow-lan: true
external-controller: '127.0.0.1:9090'
ipv6: true
tcp-concurrent: true
unified-delay: true
global-client-fingerprint: chrome
keep-alive-interval: 15
geodata-mode: true

dns:
  enable: true
  ipv6: true
  default-nameserver: [223.5.5.5, 119.29.29.29]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
  fallback: ['https://dns.alidns.com/dns-query', 'https://doh.pub/dns-query']
  fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff: 
    HTTP: 
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 5228, 8443]
  force-domain:
    - 'mtalk.google.com'
    - 'alt1-mtalk.google.com'
    - 'alt2-mtalk.google.com'
    - 'alt3-mtalk.google.com'
    - 'alt4-mtalk.google.com'
    - 'alt5-mtalk.google.com'
    - 'alt6-mtalk.google.com'
    - 'alt7-mtalk.google.com'
    - 'alt8-mtalk.google.com'
    - 'dl.google.com'
    - 'dl.l.google.com'

  tun:
  enable: true
  stack: mixed
  dns-hijack: [any:53]
