mixed-port: 7893
socks-port: 2325
tcp-concurrent: true
allow-lan: true
ipv6: false
log-level: info
find-process-mode: always
unified-delay: true
global-client-fingerprint: chrome
disable-keep-alive: false

geodata-mode: true
geox-url:
  geoip: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb"
  asn: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-ASN.mmdb"

profile: { store-selected: true, store-fake-ip: false }
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff: 
    HTTP: 
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 5228, 8443]
  force-domain:
    - 'mtalk.google.com'
    - 'alt1-mtalk.google.com'
    - 'alt2-mtalk.google.com'
    - 'alt3-mtalk.google.com'
    - 'alt4-mtalk.google.com'
    - 'alt5-mtalk.google.com'
    - 'alt6-mtalk.google.com'
    - 'alt7-mtalk.google.com'
    - 'alt8-mtalk.google.com'
    - 'dl.google.com'
    - 'dl.l.google.com'

tun:
  enable: true
  stack: mixed                # system/gvisor/mixed
  dns-hijack:
    - "any:53"
  auto-route: true
  auto-detect-interface: true
        
dns:
  enable: true
  prefer-h3: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    ["geosite:cn", "+.lan", "+.local", "+.localhost", "+.direct", "+.example", "+.invalid", "+.test", "+.home.arpa", "time.*.com", "time.*.gov", "time.*.edu.cn", "time.*.apple.com", "time-ios.apple.com", "time1.*.com", "time2.*.com", "time3.*.com", "time4.*.com", "time5.*.com", "time6.*.com", "time7.*.com", "ntp.*.com", "ntp1.*.com", "ntp2.*.com", "ntp3.*.com", "ntp4.*.com", "ntp5.*.com", "ntp6.*.com", "ntp7.*.com", "+.time.edu.cn", "+.ntp.org.cn", "+.pool.ntp.org", "time1.cloud.tencent.com", "+.msftconnecttest.com", "+.msftncsi.com", "stun.*.*", "stun.*.*.*", "+.stun.*.*", "+.stun.*.*.*", "+.stun.*.*.*.*", "+.stun.*.*.*.*.*"]
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  direct-nameserver:
    - system
  nameserver-policy:
    geosite:cn, private:
      - https://223.5.5.5/dns-query
      - https://120.53.53.53/dns-query
    geosite:gfw, geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
  respect-rules: true       
  proxy-server-nameserver:  
    - https://223.5.5.5/dns-query
    - https://120.53.53.53/dns-query
  fallback:  
    - tls://8.8.4.4
    - tls://1.1.1.1
  fallback-filter:          
    geoip: true
    geoip-code: cn
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"

